const Case = require('../models/Case');
const Complaint = require('../models/Complaint');
const { generateLegalDocument } = require('../services/AiService');

// GENERATE LEGAL DOCUMENT FOR A CASE
const generateDocument = async (req, res) => {
  try {
    const caseDoc = await Case.findById(req.params.caseId);

    if (!caseDoc) {
      return res.status(404).json({ success: false, message: 'Case not found' });
    }

    if (caseDoc.documentGenerated) {
      return res.status(200).json({
        success: true,
        message: 'Document already generated',
        data: caseDoc.legalDocument
      });
    }

    // Get all complaints for this case
    const complaints = await Complaint.find({ caseId: caseDoc._id });

    if (complaints.length === 0) {
      return res.status(400).json({ success: false, message: 'No complaints found for this case' });
    }

    // Generate document using Claude
    const document = await generateLegalDocument(caseDoc, complaints);

    // Add disclaimer
    const disclaimer = `DISCLAIMER: This document was generated by AI for informational purposes only. It does not constitute legal advice. Please consult a qualified legal practitioner before taking formal action.\n\n`;
    const finalDocument = disclaimer + document;

    // Save to case
    await Case.findByIdAndUpdate(caseDoc._id, {
      legalDocument: finalDocument,
      documentGenerated: true,
      status: 'document_generated',
    });

    res.status(200).json({
      success: true,
      message: 'Legal document generated successfully',
      data: finalDocument
    });

  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// GET EXISTING DOCUMENT FOR A CASE
const getDocument = async (req, res) => {
  try {
    const caseDoc = await Case.findById(req.params.caseId);

    if (!caseDoc) {
      return res.status(404).json({ success: false, message: 'Case not found' });
    }

    if (!caseDoc.documentGenerated) {
      return res.status(400).json({
        success: false,
        message: 'Document not yet generated. Threshold not reached.'
      });
    }

    res.status(200).json({
      success: true,
      data: caseDoc.legalDocument
    });

  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

module.exports = { generateDocument, getDocument };